services:
  - type: web
    name: seditiousthoughts-comments
    image: umputun/remark42:latest
    plan: free
    envVars:
      - key: REMARK_URL
        value: "https://seditiousthoughts-comments.onrender.com"
      - key: SITE
        value: "seditiousthoughts"
      - key: SECRET
        generateValue: true
      - key: AUTH_ANON
        value: "true"
      - key: STORE_BOLT_PATH
        value: "/tmp/data"
