services:
  - type: web
    name: seditiousthoughts-comments
    env: docker
    plan: free
    disk:
      name: remark_data
      mountPath: /srv/var
      sizeGB: 1
    envVars:
      - key: SITE_ID
        value: seditiousthoughts
      - key: AUTH_ANON
        value: "true"
      - key: UMASK
        value: "0022"
      - key: SECRET
        generateValue: true
      - key: SKIP_BACKEND_TEST
        value: "true"
      - key: SKIP_FRONTEND_TEST
        value: "true"
      - key: SKIP_FRONTEND_BUILD
        value: "true"
