services:
  - type: web
    name: seditiousthoughts-comments
    env: docker
    plan: free
    disk:
      name: remark_data
      mountPath: /srv/var
      sizeGB: 1
    envVars:
      - key: SITE_ID
        value: seditiousthoughts
      - key: SECRET
        generateValue: true
      - key: AUTH_ANON
        value: "true"
      - key: UMASK
        value: "0022"
      - key: URL
        value: https://seditiousthoughts-comments.onrender.com
    build:
      dockerfilePath: Dockerfile
      args:
        SKIP_BACKEND_TEST: "true"
        SKIP_FRONTEND_TEST: "true"
        SKIP_FRONTEND_BUILD: "true"
